import { Worker, Job } from 'bullmq';
import { redisConnection } from '../lib/redis';
import { prisma } from '../lib/prisma';
import { logger } from '../lib/logger';

export class ContentGenerationWorker {
  private worker: Worker | null = null;

  async start() {
    this.worker = new Worker(
      'content-generation',
      async (job: Job) => {
        logger.info(`Processing content generation job: ${job.id}`);
        return this.generateContent(job.data);
      },
      { connection: redisConnection, concurrency: 3 },
    );

    this.worker.on('completed', (job) => {
      logger.info(`Content generation job ${job.id} completed`);
    });

    this.worker.on('failed', (job, err) => {
      logger.error(`Content generation job ${job?.id} failed`, err);
    });

    logger.info('ContentGenerationWorker started');
  }

  private async generateContent(data: { topicId?: string; type: string; platform?: string; userId: string }) {
    const { topicId, type, platform, userId } = data;

    let topicTitle = 'General Content';
    if (topicId) {
      const topic = await prisma.topic.findUnique({ where: { id: topicId } });
      if (topic) topicTitle = topic.title;
    }

    const generatedBody = `[AI Generated] ${type} content about "${topicTitle}" optimized for ${platform || 'all platforms'}. This content was auto-generated by the content pipeline and is ready for review.`;

    const content = await prisma.content.create({
      data: {
        userId,
        topicId: topicId || undefined,
        type: type as any,
        title: `Auto: ${topicTitle}`,
        body: generatedBody,
        platform: platform as any || undefined,
        status: 'DRAFT',
        metadata: { generatedAt: new Date().toISOString(), automated: true },
      },
    });

    logger.info(`Generated content ${content.id} for topic "${topicTitle}"`);
    return { contentId: content.id };
  }

  async stop() {
    if (this.worker) {
      await this.worker.close();
      logger.info('ContentGenerationWorker stopped');
    }
  }
}
